name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-messagepack:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v2  
    - run: cd Unity/Packages/Cheetah\ MessagePack
    - run: pwd
    - run: ls         
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.cheetah.games'    
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.token_registry_cheetah_games }}
